### ISSUE TITLE
Добавить .editorconfig

### ISSUE THREAD

**Issue by h4** [web-standards-ru/logo#2]
Правил README.md. Вим у меня во все файлы добавляет пустую строку в конец файла и я долго не мог понять, почему в пулл-риквест приехало две правки вместо одной.

Мне кажется, .editorconfig мог бы тут помочь.

**Comment by pepelsbey** [comment]
Кому-то просто нужно перестать пользоваться тесктовыми редакторами XIX века ;)

Добавлю, не думал об этом — тут мало кода.

**Comment by miripiruni** [comment]
@pepelsbey бла-бла-бла... ;)

**Comment by pepelsbey** [comment]
@miripiruni, ну а что это за редактор, который не задавая вопросов вставляет то, что ты не просишь вставлять? С аргументацией «потомушта».

**Comment by h4** [comment]
@pepelsbey не-не-не, это я его так настроил. Он по дефолту так вроде бы не должен делать. Да, @miripiruni?

**Comment by miripiruni** [comment]
@h4, и пусть добавляет.

Я просто оставлю это здесь, мои дорогие любители стардартов http://stackoverflow.com/questions/729692/why-should-files-end-with-a-newline

**Comment by h4** [comment]
![image](https://cloud.githubusercontent.com/assets/430023/9996766/45b40960-6091-11e5-8f37-12feeb5d4f7f.png)

**Comment by pepelsbey** [comment]
@miripiruni, когда-то чёрный экран с текстовым вводом был стандартом и никто не врубался, зачем какие-то иконки с папочками рисовать. Vim из тех времён и я каждый раз вздрагиваю, когда с ними соприкасаюсь. Если ты пришёл добавить запятую, но вместо этого добавил ещё символ в конце файла, которого не было — ты поступил неправильно, точка.

**Comment by miripiruni** [comment]
@pepelsbey мне кажется, я не хочу разрушать свою иллюзию, что ты понимаешь, что существуют всякие настройки в разных программах.

**Comment by pepelsbey** [comment]
Fixed by ef7eb36
